# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e47e582b1dfdef6b8c502a5758cb82e9dfc21c8a21dd5527b8de1d91808cb69f2fec75f538e5b3f7d7464160b8da8ff41cbe3fc55cbbfd4df4f2de1f7fe6138f

test:
  secret_key_base: 82b0b3f197f57f594e04763417bd6f1e4a503f9a1653cb5aadceb2e4f395ae3b78cbd3e646377a1f1201bca0131ec4a3687848cf5e826a62dc1a0e6eba5a429b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
